### PR TITLE
Add support for sae package manager

### PR DESCRIPTION
**Pull request by Mr-Andersen**
There is an experimental package manager: https://github.com/DoctorRyner/sae. It would be nice to have your lib as part of its ecosystem :)
It has pretty nice features, you can keep different versions of same package at the same time

### CODE REVIEW

**Comment by Mr-Andersen** [comment]
If it's ok, i'll make same PR for `elab-deriving`

**Comment by MarcelineVQ** [comment]
This is the first I've heard of sae but I like what I see from it so far.
I'm open to including extra files like Eq.yml to support build tools like sae but I'm not really okay with it modifying the project's .ipkg file instead of generating a separate one. e.g. generating a curl-0_16_3_0.ipkg instead of replacing the contents of curl.ipkg

I've made an issue here https://github.com/DoctorRyner/sae/issues/1 and if that's addressed to not modify the original ipkg then I'm more than happy to include Eq.yml

**Comment by MarcelineVQ** [comment]
Based on the linked discussion I've decided to change how I structure projects by naming the ipkg of a project `package.ipkg` and letting the fields within it define the package name. To that end I'm fine with you including Eq.yml on projects you prefer but it's best to leave the generated ipkg files out of the repo since tooling will make them anyway.

**Comment by MarcelineVQ** [comment]
I went ahead and added the support while I'm adding it for other projects, thanks for bringing this topic up!

**Comment by MarcelineVQ** [comment]
@Mr-Andersen  I just wanted to mention you should check out https://github.com/stefan-hoeck/idris2-elab-util if you haven't

**Comment by Mr-Andersen** [comment]
Thank you! This is great

**Pull request closed without merging**
